runtime: python311
service: emotec-backend

instance_class: F4

# Increase timeout for ML operations
automatic_scaling:
  max_instances: 1
  min_instances: 0

env_variables:
  PYTHONUNBUFFERED: "1"

# Required for GPU access (uncomment if needed)
# resources:
#   cpu: 1
#   memory_gb: 4
#   gpu:
#     type: nvidia-tesla-t4
#     count: 1
